@url = http://165.232.173.215:9088
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGYxNTg0Nzg3YmRlZDY3NmVlOTQ3YTgiLCJpYXQiOjE2MjY0Mjk1MjAsImV4cCI6MTYyODE1NzUyMH0.ySfWgaJ4L_vrF8YraZIBN0iOtNaqARffe3uQiO3sU-I
POST {{url}}/app/register
Content-Type: application/json

{
    "username":"helloworld",
    "email":"helloworld@gmail.com",
    "password":"123123123",
    "confirm_password":"123123123"
}

###
POST {{url}}/app/login
Content-Type: application/json

{
    "username":"helloworld",
    "password":"123123123"
}

###
GET {{url}}/api/user/profile
Authorization: {{token}}

# 5f212f8b3f91c81672d7f398 confirm


###
POST {{url}}/api/user/change-password
Content-Type: application/json
Authorization: {{token}}

{
    "password":"123123123",
    "new_password":"bank111998",
    "confirm_password":"bank111998"
}


###
POST {{url}}/api/list-product
Content-Type: application/json
Authorization: {{token}}

{
    "limit": 20,
    "page": 1

}